### ISSUE TITLE
Not sure if the search is working

### ISSUE THREAD

**Issue by agarrharr** [riyadhalnur/weather-cli#1]
It would be nice if the results told me which city it's showing me. For example if I run `weather-cli`, I get

```
Condition: Haze
Temperature: 22C/71F
```

and I'm not sure what city this is. Or if I run `weather-cli new`, I get:

```
Condition: Rain/Windy
Temperature: 23C/74F
```

I'm not sure what city this is. It could be New York, New Mexico, or somewhere else.

**Comment by riyadhalnur** [comment]
The default is Dhaka, Bangladesh but I get what you mean. Thanks for the heads up
