### ISSUE TITLE
how can i change my default city

### ISSUE THREAD

**Issue by 11philip22** [riyadhalnur/weather-cli#117]
how can i change my default city

**Comment by riyadhalnur** [comment]
At the moment, it's not possible to change the defaults. That said, that can be a new feature in the next version. Thank you for the idea.

**Comment by 11philip22** [comment]
I fixed my issue with a bash script.
I made a file in /usr/local/bin/ called weer witch is weather in my language
and just put this in it: 

```

#!/bin/bash

weather Groningen Netherlands
```

Groningen = city 
Netherlands = country

I hope this helps newbies like me who have the same question.

**Comment by riyadhalnur** [comment]
Reopening this because I would like to include this feature in the next upcoming version.
