### ISSUE TITLE
[REJECTED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [riyadhalnur/weather-cli#119]
Dear Riyadh,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by riyadhalnur** [comment]
Could you explain why that will be useful? If you'd like to generate an executable for personal use, you can by using `pkg` from zeit, easily. Download or git clone this repo and pass in the `package.json` to `pkg`.
