### ISSUE TITLE
config should also let me set the scale and remember it

### ISSUE THREAD

**Issue by mschwartz** [riyadhalnur/weather-cli#139]
I like being able to set my default location.
I prefer to see temperature in Fahrenheit always.

So instead of having to type "weather -s f"
I'd like to type "weather config -c ... -C ... -s f"
and then when I type "weather" I get the display I want.

Thanks for this.

**Comment by Wintaru** [comment]
I'd be up for this too, in the main time I'll set an alias I guess.

**Comment by riyadhalnur** [comment]
Thanks for the request. Sounds like a useful feature. Next release will contain it :smiley:

**Comment by riyadhalnur** [comment]
Added in new version v1.4.0

**Comment by mschwartz** [comment]
Thanks!
