### ISSUE TITLE
Project name error

### ISSUE THREAD

**Issue by pnodet** [riyadhalnur/weather-cli#149]
Javascript error when using weather cli

<img width="839" alt="Capture d’écran 2019-08-18 à 18 08 40" src="https://user-images.githubusercontent.com/5941125/63227100-5a67cd80-c1e3-11e9-920d-b6a2e29f6272.png">

**Comment by riyadhalnur** [comment]
Thank you for reporting this. I'll release a new version with the fix soon.

**Comment by riyadhalnur** [comment]
Patch with fix - **v1.4.2** released :smiley:
