### ISSUE TITLE
Provide ability to select from list of ambiguous results

### ISSUE THREAD

**Issue by dsbert** [riyadhalnur/weather-cli#155]
Right now you can only search by city and country. The name of my city is somewhat generic and there are a lot of results, and mine is not the first in the list. It would be great to have the ability to choose from a list, or at the very least, set the city by coordinates instead of city and country name.

**Comment by dsbert** [comment]
It looks like if I search directly on open weather and provide the state, it will return with the exact city I am looking for. `City, State, Country`.

Is this the same as `-c "City, State" -C Country`?

**Comment by riyadhalnur** [comment]
Hi, thanks for pointing this out. Can you provide the location you're trying to locate? This is certainly something worth adding to the program.

**Comment by dsbert** [comment]
You can use Portland as an example. There is `Portland, Oregon, US` on the West coast and `Portland, ME, US` on the East coast.

https://openweathermap.org/find?q=portland

**Comment by riyadhalnur** [comment]
You can use the state code next to the city for cases you provided, e.g city=Portland,OR and country=US to get specific results.

**Comment by dsbert** [comment]
Good to know, might be worth adding that as part of the API help text. Thank you
